[window]
opacity = 0.95
blur = true
decorations = "none"
padding = { x = 0, y = 0 }

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors.primary]
background = '#030303'
foreground = '#cdcdcd'

[colors.normal]
black = '#252530'
red = '#d8647e'
green = '#7fa563'
yellow = '#f3be7c'
blue = '#6e94b2'
magenta = '#bb9dbd'
cyan = '#aeaed1'
white = '#cdcdcd'

[colors.bright]
black = '#606079'
red = '#e08398'
green = '#99b782'
yellow = '#f5cb96'
blue = '#8ba9c1'
magenta = '#c9b1ca'
cyan = '#bebeda'
white = '#d7d7d7'

[terminal]
shell = { program = "/home/abhishek/.cargo/bin/nu", args = [
  "--config",
  "~/.config/nushell/config.nu",
] }
